# Generated by Django 4.0.4 on 2022-04-30 08:05

import album.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('poster', models.ImageField(upload_to=album.utils.uploader, validators=[album.utils.ImageValidator(content_types=('image/png', 'image/jpeg', 'image/jpg'), max_size=5242880)])),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кратокое описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фото')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to=album.utils.uploader, validators=[album.utils.ImageValidator(content_types=('image/png', 'image/jpeg', 'image/jpg'), max_size=5242880)], verbose_name='Загрузить фото в альбом')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='album.album', verbose_name='В какой альбом загрузить?')),
                ('tags', models.ManyToManyField(to='album.tags', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Изображение альбома',
                'verbose_name_plural': 'Изображения альбома',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(to='album.tags', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
